config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  resources :organisations, param: :slug do
    resources :events, only: [:index] # greenpeace/events
    resources :jobs, only: [:index] # greenpeace/jobs
    get 'jobs/available', to: 'jobs#index_available'
  end

  resources :events do
    get 'jobs/available', to: 'jobs#index_available'
    resources :jobs #monday_janboree/jobs/1/edit..
  end

  resources :jobs, only: [:index]
  get 'jobs/available', to: 'jobs#index_available'
  get 'jobs/longesttitle', to: 'jobs#longest_title'
  
  root to: "welcome#home"

end

app/models/organisation.rb
class Organisation < ApplicationRecord
    has_many :events 
    belongs_to :owner, class_name: "User" 
    has_many :volunteers, through: :events, foreign_key: "user_id"
    has_many :jobs, through: :events
    validates :name, presence: true
    validates :location, presence: true

    def slug
        self.name.downcase.strip.gsub(' ', '-')
    end

    def self.find_by_slug(slug)
        self.all.find{|object| object.slug == slug}
    end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
    before_action :set_organisation, only: [:show, :edit, :destroy, :update]

    def index
        @orgs = Organisation.all
    end

    def show
        @organisation = Organisation.find_by_slug(params[:slug])
    end

    def new
        @organisation = Organisation.new
        authorize @organisation
        
    end

    def create
        @organisation = Organisation.new(organisation_params)
        @organisation.owner = current_user
        current_user.organisation = @organisation
        if @organisation.save && current_user.save
            redirect_to organisation_path(@organisation.slug)
        else
            render 'new'
        end
    end

    def edit
        authorize @organisation
    end

    def update
        authorize @organisation
        if @organisation.update(organisation_params)
            redirect_to organisation_path(@organisation.slug)
        else
            render 'edit'
        end
    end

    def destroy
        authorize @organisation
        @organisation.destroy
        redirect_to organisations_path
    end

    private

    def set_organisation
        @organisation = Organisation.find_by_slug(params[:slug])
    end

    def organisation_params
        params.require(:organisation).permit(:name, :location, :mission, :category, :website, :contact_info)
    end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper

    def categories
        ["Environmental", "Health", "Animal welfare", "Disability services", "Social welfare", "Other"]
    end
end

app/views/organisations/_display_organisation.html.erb
 <div class="org-display">

 <h1><%= link_to org.name, organisation_path(org.slug)%></h1>

 <h3><%= org.location %></h3>

 <p>Category: <%= org.category %></p>

 <p>Visit our website: <%= org.website %></p>
 <p><%= org.contact_info %></p>
 <p><%= org.mission %></p>
<% if current_user == org.owner%>
    <%= link_to "Edit Organisation", edit_organisation_path(org.slug), class:"btn btn-outline-warning btn-sm" %>
    <%= link_to "Delete Organisation", organisation_path(org.slug), method:"DELETE", data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %>
<% end%>
 </div>

app/views/organisations/_organisation_fields.html.erb
<%= f.input :name %>
<%= f.input :location %>
<%= f.input :mission %>
<%= f.input :website %>
<%= f.input :contact_info, as: :text %>
<%= f.input :category, collection: categories %>
<%= f.button :submit, class:"btn btn-primary" %>

app/views/organisations/edit.html.erb
<h1>Edit Organisation</h1>
<br>
<%= simple_form_for [@organisation], url: organisation_path(@organisation.slug) do |f| %>
    <%= render 'organisation_fields', f: f %>
<% end %>

app/views/organisations/index.html.erb
<h1>Organisations</h1>
<br>
<ul class="list-group">
    <% @orgs.each do |org|%>
        <li class="list-group-item"> 
        <%= render 'display_organisation', org: org %>
        </li>
    <% end%>
</ul>


app/views/organisations/new.html.erb
<h1>Create a New Organisation</h1>
<br>
<%= simple_form_for [@organisation] do |f| %>
   <%= render 'organisation_fields', f: f %>
<% end %>

app/views/organisations/show.html.erb
<%= render 'display_organisation', org: @organisation %>
<br>
<%= link_to "Our Events", organisation_events_path(@organisation.slug) %>
<br>
<%= link_to "Our Jobs", organisation_jobs_path(@organisation.slug) %>
<br>
<%= link_to "Create New Event", new_event_path %>