config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  resources :organisations, param: :slug do
    resources :events, only: [:index] # greenpeace/events
    resources :jobs, only: [:index] # greenpeace/jobs
    get 'jobs/available', to: 'jobs#index_available'
  end

  resources :events do
    get 'jobs/available', to: 'jobs#index_available'
    resources :jobs #monday_janboree/jobs/1/edit..
  end

  resources :jobs, only: [:index]
  get 'jobs/available', to: 'jobs#index_available'
  get 'jobs/longesttitle', to: 'jobs#longest_title'
  
  root to: "welcome#home"

end

app/models/job.rb
class Job < ApplicationRecord
    belongs_to :event, optional:true
    belongs_to :volunteer, optional:true, class_name: "User", foreign_key: "user_id"
    validates :title, presence: true
    validates :description, presence: true
    validates :work_type, presence: true
    validates :commitment, presence: true
    validates :volunteer, presence: { message: "must be provided if job is assigned" }, if: -> { assigned } 
    validates :volunteer, absence: { message: "must be blank if job is un-assigned" }, if: -> { !assigned } 
    scope :available, -> { where(assigned: false)}

    scope :longesttitle, -> { where(MAX(LENGTH(title))) }
 
    #order("MAX(CHAR_LENGTH(first_name)) desc").limit(1)
    def organisation
        self.event.organisation
    end
    
    def organisation=(organisation)
        self.event.organisation = organisation
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :set_job, only: [:show, :edit, :update, :destroy]
    before_action :set_event, only: [:show, :create, :new, :edit, :update]
    
    def show
        @organisation = @job.organisation
    end

    def new
        @job = @event.jobs.build
        authorize @job
    end

    def index
        if params[:organisation_slug]
            @organisation = Organisation.find_by_slug(params[:organisation_slug])
            @jobs = @organisation.jobs
        elsif params[:event_id]
            @event = Event.find(params[:event_id])
            @jobs = @event.jobs
        else
            @jobs = Job.all
        end
    end

    def index_available
        if params[:organisation_slug]
            @organisation = Organisation.find_by_slug(params[:organisation_slug])
            @jobs = @organisation.jobs.available
        elsif params[:event_id]
            @event = Event.find(params[:event_id])
            @jobs = @event.jobs.available
        else
            @jobs = Job.available
        end
        render 'index'
    end

    def longest_title
        @job = Job.longesttitle.first  
    end

    def create
        @job = @event.jobs.build(job_params)
        authorize @job
        if @job.save
            redirect_to event_path(@event)
        else
            render 'new'
        end
    end

    def edit
        authorize @job
    end

    def update
        authorize @job
        if @job.update(job_params)
            redirect_to event_job_path(@event, @job)
        else
            render 'edit'
        end
    end

    def destroy
        @job.destroy
        redirect_to event_jobs_path
    end

    private
    
    def set_job
        @job = Job.find(params[:id])
    end

    def set_event
        @event = Event.find(params[:event_id])
    end

    def job_params
        params.require(:job).permit(:title, :event_id, :user_id, :description, :assigned, :work_type, :location, :commitment)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
    def locations
        Job.all.map{|job| job.location}.uniq!.compact
    end
end

app/views/jobs/_display_jobs.html.erb
<ul class="list-group">
    <% jobs.each do |job|%>
        <li class="list-group-item"> 
            <h3><%= link_to job.title, event_job_path(job.event, job) %> 
            <% if job.assigned%>
                <span class="badge badge-pill badge-secondary">Assigned</span>
            <% end %></h3> 
            <p><strong>Organisation:</strong> <%= job.organisation.name %>
            <br>
            <strong>Location:</strong> <%= job.location %>
            <br>
            <strong>Work Type:</strong> <%= job.work_type %>
            <br>
            <strong>Required Commitment:</strong> <%= job.commitment %></p>
            <p><%= job.description %></p>
            <% if current_user == job.organisation.owner %>
                <div class="btn-group list-group-horizontal-sm">
                    <%= link_to "Edit Job", edit_event_job_path(job.event, job), class:"btn btn-outline-warning btn-sm" %>
                    <%= link_to "Delete Job", event_job_path(job.event, job), method:"DELETE", data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %> <br>
                </div>
             <% end%>
        </li>
    <% end%>
</ul>

app/views/jobs/_form.html.erb
<%= simple_form_for [@event, @job] do |f| %>
  <%= render 'events/job_fields', f: f %>
  <%= f.button :submit, class:"btn btn-primary"  %>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>
<br>
<%= render 'form' %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>
<br>
<h3>Filter by:</h3>
<% if @organisation%>
    <%= link_to "Available Jobs", organisation_jobs_available_path(@organisation.slug) %>
    <br>
    <%= link_to "All Jobs", organisation_jobs_path(@organisation.slug) %>
<% else%>
    <%= link_to "Available Jobs", jobs_available_path %>
    <br>
    <%= link_to "All Jobs", jobs_path %>
<% end%>
<br>

<% if @jobs.empty?%>
    <p>Sorry we don't have any jobs right now, check back later.</p>
<% else%>
    <%= render 'display_jobs', jobs: @jobs %>
    <% if @event%>
        <%=link_to "Create a new Job", new_event_job_path(@event), class:"btn btn-outline-primary btn-sm" if user_signed_in? && current_user == @event.organisation.owner%>
    <% end%>
<% end%>

app/views/jobs/longest_title.html.erb
<h1>Job with longest title award goes to: <%= @job.title %> </h1>
<br>

<h5>Location: <%= @job.location if @job.location%> </h5>
<br>
<h5>Type of work: <%= @job.work_type if @job.work_type%> </h5>
<br>
<h5>Time commitment required: <%= @job.commitment if @job.commitment%> </h5>
<br>
<h5><%= @job.description %> </h5>
<br>

app/views/jobs/new.html.erb
<h1>Create a New Job</h1>
<br>
<%= render 'form' %>

app/views/jobs/show.html.erb
<h1><%= @job.title %> </h1>
<br>
<h4>Event:  <%=link_to @event.name, event_path(@event) %> </h4>
<h5>by: <%= @event.organisation.name%> </h5>
<h5><%= @event.datetime%> </h5>
<br>
<h5>Location: <%= @job.location if @job.location%> </h5>
<br>
<h5>Type of work: <%= @job.work_type if @job.work_type%> </h5>
<br>
<h5>Time commitment required: <%= @job.commitment if @job.commitment%> </h5>
<br>
<h5><%= @job.description %> </h5>
<br>

<% if !user_signed_in? %>
  <%= link_to "Sign in or register to apply for this job", new_user_session_path %>
<% elsif @job.assigned  %>
  <% if current_user == @job.volunteer %>
      <p class="alert alert-success">This job is assigned to: <%= @job.volunteer.name %></p>
      <%= simple_form_for [@event, @job] do |f| %>
        <%= f.hidden_field :assigned, value: false %>
        <%= f.hidden_field :user_id, value: nil %>
        <%= f.button :submit, "Dont want to work this anymore?", class:"btn btn-danger", data: { confirm: 'Are you sure?' }  %>
      <% end %>
  <% else%>
    <p class="alert alert-warning">Sorry this job is already assigned to: <%= @job.volunteer.name %></p>
  <% end %>
<% else %>
  <%= simple_form_for [@event, @job] do |f| %>
    <%= f.hidden_field :assigned, value: true %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.button :submit, "Take this job", class:"btn btn-primary"  %>
    <br>
  <% end%>
<% end%>
<br>

<% if current_user == @organisation.owner %>
  <ul class="list-group list-group-horizontal-sm">
  <%= link_to "Edit Job", edit_event_job_path, class:"btn btn-outline-warning btn-sm" %> <br>
  <%= link_to "Delete Job", event_job_path, method:"DELETE", data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %><br>
  </ul>
<% end %>