config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  resources :organisations, param: :slug do
    resources :events, only: [:index] # greenpeace/events
    resources :jobs, only: [:index] # greenpeace/jobs
    get 'jobs/available', to: 'jobs#index_available'
  end

  resources :events do
    get 'jobs/available', to: 'jobs#index_available'
    resources :jobs #monday_janboree/jobs/1/edit..
  end

  resources :jobs, only: [:index]
  get 'jobs/available', to: 'jobs#index_available'
  get 'jobs/longesttitle', to: 'jobs#longest_title'
  
  root to: "welcome#home"

end

app/views/shared/_navigationbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
      <a class="navbar-brand" href="/">Volunteer Board</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
 
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

         <li class="nav-item">
            <%= link_to "Organisations", organisations_path, class:"nav-link nav-top-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Events", events_path, class:"nav-link nav-top-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Jobs", jobs_path, class:"nav-link nav-top-link" %>
          </li>

          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle nav-top-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Make a new...
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Event", new_event_path, class:"dropdown-item" if current_user.organisation %>
                <%= link_to "Organisation", new_organisation_path, class:"dropdown-item" %>
            </li>
            </ul>

            <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to 'Sign-out', destroy_user_session_path, method: :delete, class:"nav-link nav-top-link" %>
            </li>
            <li class="nav-item">
                <%= link_to 'User Account', edit_user_registration_path, class:"nav-link nav-top-link" %>
            </li>

          <% else%>
            </ul>
            <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <%= link_to 'Sign-in', new_user_session_path, class:"nav-link nav-top-link" %>
            </li>
            <li class="nav-item">
                <%= link_to 'Sign-up', new_user_registration_path, class:"nav-link nav-top-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, class:"nav-link nav-top-link" %>
            </li>
          <% end%>
          
          </ul>
      </div>
</nav>