config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  resources :organisations, param: :slug do
    resources :events, only: [:index] # greenpeace/events
    resources :jobs, only: [:index] # greenpeace/jobs
    get 'jobs/available', to: 'jobs#index_available'
  end

  resources :events do
    get 'jobs/available', to: 'jobs#index_available'
    resources :jobs #monday_janboree/jobs/1/edit..
  end

  resources :jobs, only: [:index]
  get 'jobs/available', to: 'jobs#index_available'
  get 'jobs/longesttitle', to: 'jobs#longest_title'
  
  root to: "welcome#home"

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organisation #an organisation is holding the event
  has_many :jobs, dependent: :destroy
  has_many :volunteers, through: :jobs, foreign_key: "user_id"
  accepts_nested_attributes_for :jobs, allow_destroy: true
  
  validates :name, presence: true
  validates :date, presence: true
  validates :location,  presence: true

  def datetime
    self.date.strftime("%m:%M %p, %A %e %B, %Y")
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :set_event, only: [:show, :edit, :update, :destroy]
    
    def index
        if params[:organisation_slug]
            @organisation = Organisation.find_by_slug(params[:organisation_slug])
            @events = @organisation.events
        else
            @events = Event.all
        end
    end

    def new
        @event = Event.new
        authorize @event
        @job = @event.jobs.build
    end

    def create
        @event = Event.new(event_params)
        authorize @event
        if @event.save
            redirect_to event_path(@event)
        else
            render 'new'
        end
    end

    def show
    end

    def edit
        authorize @event
    end

    def update
        authorize @event
        if @event.update(event_params)
            redirect_to event_path(@event)
        else
            render 'edit'
        end
    end

    def destroy
        authorize @event
        @event.destroy
        redirect_to events_path
    end

    private

    def event_params
        params.require(:event).permit(:organisation_id, :name, :date, :location, :information, jobs_attributes: [:id, :title, :event_id, :user_id, :description, :assigned, :work_type, :location, :commitment, :_destroy])
    end

    def set_event
        @event = Event.find(params[:id])
    end

end

app/helpers/events_helper.rb
module EventsHelper

    def types
        ["Labouring", "Admin", "IT", "Childcare", "Working with animals", "Aged care", "Gardening", "Marketing", "Disability Support"]
    end
end

app/views/events/_display_event.html.erb
<h1><%= link_to event.name, event_path(event) %></h1>
    
<h4>by: 
<%= link_to event.organisation.name, organisation_path(event.organisation.slug) %></h4>

<p><%= event.datetime %></p>

<p><%= event.location %> </p>

<p><%= event.information %></p>






app/views/events/_form.html.erb
<%= simple_form_for [@event] do |f| %>
    <%= f.input :name %>
    <%= f.input :date, as: :date, html5: true %>
    <%= f.input :location %>
    <%= f.input :information %>
    <%= f.hidden_field :organisation_id, value: current_user.organisation.id %>
    <h4>Event Jobs:</h4>
    <div class='jobs'>
        <%= f.simple_fields_for :jobs do |job| %>
            <%= render 'job_fields', f: job %>
        <% end%>
    </div>
    <br>
    <div class="btn-group">
    <%= link_to_add_association 'Add Job', f, :jobs, data: { association_insertion_node: '.jobs', association_insertion_method: :append }, class:"btn btn-outline-primary"   %>
    <%= f.button :submit, class:"btn btn-primary" %>
    </div>
<% end%>
 

app/views/events/_job_fields.html.erb
<div class='nested-fields'>
    <%= f.input :title, label:"Job Title"%>
    <%= f.input :description, as: :text, label:"Job Description" %>
    <%= f.input :assigned, as: :radio_buttons, default: false %>
    <%= f.input :work_type, collection: types, label:"Select job type of work"%>
    <%= f.hidden_field :location, value: @event.location %>
    <%= f.input :commitment, collection: ["part-time", "full-time", "one-off event", "recurring event"], label:"Job commitment"%>
    <%= f.association :volunteer, hint: "If assigned then who is this job assigned to?" %>
    <%= link_to_remove_association "Remove job", f, class:"btn btn-outline-danger btn-sm" %>
</div>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form" %>

app/views/events/index.html.erb
<h1>Events</h1>
<br>
<%= link_to "Create a new event", new_event_path, class:"btn btn-outline-primary btn-sm" if user_signed_in? && current_user.organisation %>
<% if @events.empty? %>
<br>
<br>
    <p>Sorry we don't have any events right now</p>
<% else%>
    <ul class="list-group">
        <% @events.each do |event|%>
            <li class="list-group-item"> 
            <%= render 'display_event', event: event %> 
            <% if current_user == event.organisation.owner%>
                <div class="btn-group">
                <%= link_to "Edit Event", edit_event_path(event), class:"btn btn-outline-warning btn-sm" %> <br>
                <%= link_to "Delete Event", event_path(event), method: "DELETE", data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %>
                </div>
            <% end%>
            </li>
        <% end%>
    </ul>
<% end%>



app/views/events/new.html.erb
<h1>Create a New Event</h1>

<%= render "form" %>




app/views/events/show.html.erb
<%= render 'display_event', event: @event %>

<div><h2>Jobs:</h2>
    <% if @event.jobs.present? %>
        <h5>Filter by:</h5>
        <%= link_to "Available Jobs", event_jobs_available_path(@event) %>
        <br>
        <%= link_to "All Jobs", event_jobs_path(@event) %>
        <br>
        <%= render 'jobs/display_jobs', jobs: @event.jobs %>
    <% else%>
        <p>Sorry we don't have any jobs right now, check back later. </p>
    <% end%>
</div>

<% if current_user == @event.organisation.owner %>
    <div class="btn-group">
        <%= link_to "Add Job", new_event_job_path(@event), class:"btn btn-outline-primary" %><br>
        <%= link_to "Edit Event", edit_event_path, class:"btn btn-outline-warning" %><br>
        <%= link_to "Delete Event", event_path, method:"DELETE", data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" %>
    </div>
<% end%>